# Generated by Django 4.0.5 on 2022-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(),
        ),
    ]
