# Generated by Django 4.0.5 on 2022-07-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_date_of_birth_alter_movies_release_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='Movies',
        ),
    ]
