# Generated by Django 4.0.5 on 2022-07-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actor',
            new_name='actors',
        ),
    ]
